version: '3.8'

services:
  tradebot:
    build: .
    container_name: tradebot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Персистентное хранилище для состояния и логов
      - ./logs:/app/logs
      - ./signals:/app/signals
      - ./backtests:/app/backtests
      - ./tradebot.db:/app/tradebot.db  # База данных SQLite
    # Healthcheck
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/logs') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
