services:
  tradebot:
    build: .
    container_name: tradebot
    restart: unless-stopped
    environment:
      - TZ=Europe/Samara
    env_file:
      - .env
    volumes:
      # Персистентное хранилище для состояния и логов
      - ./logs:/app/logs
      - ./signals:/app/signals
      - ./backtests:/app/backtests
      - ./data:/app/data  # Директория для базы данных
    # Healthcheck
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/logs') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build: .
    container_name: tradebot-dashboard
    restart: unless-stopped
    environment:
      - TZ=Europe/Samara
    entrypoint: []  # Переопределяем entrypoint
    command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"  # Доступ к dashboard через http://localhost:8501
    volumes:
      # Те же данные что и у основного бота
      - ./logs:/app/logs
      - ./signals:/app/signals
      - ./backtests:/app/backtests
      - ./data:/app/data
    depends_on:
      - tradebot
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
